### ISSUE TITLE
Vereiste [DO2]: neem examples op in scenario outline om de gewenste functionaliteit vast te stellen

### ISSUE THREAD

**Issue by arothuis-hu** [MiekeLidia/cisq1-lingo#1]
https://github.com/MiekeLidia/cisq1-lingo/blob/f3eaf1b77f133a1e573ff76b2b4c3bf5a6e4ecb3/src/test/resources.features/trainer.feature#L41-L43

**Comment by MiekeLidia** [comment]
hooi
